version: "3"

services:
  blog:
    build: ./packages/blog
    container_name: blog
    command: node ./app/dist/index.js
    expose: ["3010"]
    networks:
      - back-tier

  user:
    image: node:8
    command: node ./app/dist/index.js
    container_name: user
    volumes:
     - ./packages/user:/app
     - ./packages/core:/app/node_modules/core
     - ./packages/schema:/app/node_modules/schema
    expose: ["3011"]
    networks:
      - back-tier

  gateway:
    build: ./packages/gateway
    container_name: gateway
    command: node ./app/dist/index.js
    depends_on:
      - blog
      - user
    ports: ["3000:3000"]
    networks:
      - back-tier

networks:
  back-tier:
