version: "3"

services:
  blog:
    image: node:8
    working_dir: /app
    command: npm run watch:blog
    container_name: blog
    volumes:
      - .:/app
    depends_on:
      - zipkin
    expose: ["3010"]
    environment:
      - NODE_ENV=docker
      - USERADDR=http://user:3011

  user:
    image: node:8
    working_dir: /app
    command: npm run watch:user
    container_name: user
    volumes:
      - .:/app
    depends_on:
      - zipkin
    expose: ["3011"]
    environment:
      - NODE_ENV=docker
      - BLOGADDR=http://blog:3010

  gateway:
    image: node:8
    working_dir: /app
    command: npm run watch:gateway
    container_name: gateway
    volumes:
      - .:/app
    depends_on:
      - zipkin
      - blog
      - user
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
      - USERADDR=http://user:3011
      - BLOGADDR=http://blog:3010

  consul:
    image: consul
    container_name: dev-consul
    ports:
      - 8500:8500

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is enabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
  # Prometheus time series DB for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
        - "9090:9090"
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
        - "9100:9100"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
        - "8080:3000"
    depends_on:
        - prometheus