version: "3"

services:
  blog:
    image: node:8
    command: node ./app/dist/blog/index.js
    container_name: blog
    volumes:
      - .:/app
    expose: ["3010"]
    environment:
      - NODE_ENV=docker
      - USERADDR=http://user:3011
    networks:
      - back-tier

  user:
    image: node:8
    command: node ./app/dist/user/index.js
    container_name: user
    volumes:
      - .:/app
    expose: ["3011"]
    environment:
      - NODE_ENV=docker
      - BLOGADDR=http://blog:3010
    networks:
      - back-tier

  gateway:
    image: node:8
    command: node ./app/dist/gateway/index.js
    container_name: gateway
    volumes:
      - .:/app
    depends_on:
      - blog
      - user
    ports: ["3000:3000"]
    environment:
      - NODE_ENV=docker
      - USERADDR=http://user:3011
      - BLOGADDR=http://blog:3010
    networks:
      - back-tier

networks:
  back-tier:
