version: "3"

services:
  blog:
    build: .
    container_name: blog
    expose: ["3010"]
    working_dir: /app/packages/blog
    command: npm start
    networks:
      - back-tier

  user:
    build: .
    container_name: user
    working_dir: /app/packages/user
    command: npm start
    expose: ["3011"]
    networks:
      - back-tier

  gateway:
    build: .
    container_name: gateway
    working_dir: /app/packages/gateway
    command: npm start
    environment:
      - PORT=3000
      - BLOGADDR=http://blog:3010
      - USERADDR=http://user:3011
    depends_on:
      - blog
      - user
    ports: ["3000:3000"]
    networks:
      - back-tier

networks:
  back-tier:
