{
 "title": "Gateway",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_buckets_milliseconds_count{job=\"gateway\", cardinality=\"one\"}",
     "legendFormat": "{{method}} : {{status}}"
    }
   ]
  },
  {
   "title": "Gateway Request Duration (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_milliseconds{job=\"gateway\", method=\"post\", quantile=~\"0.5|0.95\", status=\"200\"}",
     "legendFormat": "{{quantile}} : {{status}}"
    }
   ]
  },
  {
   "title": "Blog Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_buckets_milliseconds_count{job=\"blog\"}",
     "legendFormat": "{{method}} : {{status}}"
    },
    {}
   ]
  },
  {
   "title": "Blog Request Duration (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_milliseconds{job=\"blog\", method=\"post\", quantile=~\"0.5|0.95\", status=\"200\"}"
    }
   ]
  },
  {
   "title": "User Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_buckets_milliseconds_count{job=\"user\"}",
     "legendFormat": "{{method}} : {{status}}"
    },
    {}
   ]
  },
  {
   "title": "User Request Duration (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_milliseconds{job=\"user\", method=\"post\", quantile=\"0.5\", status=\"200\"}"
    }
   ]
  }
 ]
}