apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    run: gateway
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30100
    protocol: TCP
  selector:
    run: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      run: gateway
  replicas: 2
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - name: gateway
        image: graphql-gateway:v0.1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "kubernetes"
        command: ["node", "./gateway/index.js"]
